# -*- coding: utf-8 -*-
"""DescensoRapido.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x5s46__6mTij2KROAdNdLR3z35kZIeCe
"""

"""
Created on Mon Nov  1 16:20:52 2021

@author: ....
"""

import numpy as np
import scipy.linalg as sl
import pandas as pd
from tabulate import tabulate

tabla = {"x": [], "p": [], "error": []}


def maximo_descenso(A, b, x0, error, iteracciones):

    xk = x0
    tabla["x"].append(xk.flatten())
    tabla["p"].append("---")
    tabla["error"].append("---")

    for i in range(iteracciones):

        dk = b - np.dot(A, xk)
        dkt = np.transpose(dk)
        Adk = np.dot(A, dk)
        pk = np.dot(dkt, dk) / np.dot(dkt, Adk)
        xk1 = xk + pk * dk
        comp = sl.norm(xk1 - xk) / sl.norm(xk1)
        tabla["x"].append(xk.flatten())
        tabla["error"].append(comp)
        tabla["p"].append(dk.flatten())
        if comp < error:
            df = pd.DataFrame(tabla)
            print(tabulate(df, headers="keys", tablefmt="psql"))
            print("Holaaaaaaaaaaaaaaaaa")
            return xk1
        xk = xk1
    df = pd.DataFrame(tabla)
    print(tabulate(df, headers="keys", tablefmt="psql"))
    return xk


A = np.array([[4, 1, 2], [3, 1, 4], [5, 1, 3]], float)
b = np.array([[40], [53], [51]], float)
x0 = np.array([[0], [0], [0]], float)

xk = maximo_descenso(A, b, x0, 0.0001, 2000)

#print(xk)
print("Comprobación")
print(f"{A @ xk} = {b}")